### ISSUE TITLE
Application complete status

### ISSUE THREAD

**Issue by tnguyen14** [tnguyen14/seo-vietnam#37]
- [x] Add 'complete' status
- [x] Add view profile button once app is complete

**Comment by nguyentran90** [comment]
Will you also get an email confirming that we receive the application?

**Comment by tnguyen14** [comment]
No. No email is implemented at this phase.

**Comment by nguyentran90** [comment]
Ok so can we add a feedback page confirming that we receive their applications?

**Comment by tnguyen14** [comment]
There is already a feedback page upon completion of the application.

**Comment by nguyentran90** [comment]
When I clicked Submit, nothing happened so i figured there was no feedback page. can you check?

**Comment by tnguyen14** [comment]
When the app is complete (all the required sections are filled in), clicking on 'Finish Application' button took me to the completed page. Please try again, it could have been a bug that was resolved in the latest deploy.

**Comment by tnguyen14** [comment]
Implemented in a87b04ce6f00b642c2ad95686d00d1e4307a1448
