### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by nguyentran90** [tnguyen14/seo-vietnam#38]
Only one file is uploaded. When you try to upload tthe second file, the first one is replaced. I think the quick fix is just to give them a message that say please combine all documents in one file and upload it. All document including unofficial transcript, resume, cover letter etc.

**Comment by tnguyen14** [comment]
I wasn't aware that there was a need to upload multiple files. This solution was made for a single file upload yes.

**Comment by tnguyen14** [comment]
@nguyentran90 Can I confirm that the other possible documents for applicants to upload are unofficial transcript and cover letter? Anything else?

**Comment by nguyentran90** [comment]
They might also upload a writing sample. But we wouldn't ask more than that 

—

**Comment by tnguyen14** [comment]
The 4 file uploads current implemented are:
- resume
- cover letter
- transcript
- writing sample
